name: Linux

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: deps
      run: sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - name: Build Linux
      run: ./make.sh all
